### ISSUE TITLE
🐛 Bug Report - Should not depend on available Internet connection

### ISSUE THREAD

**Issue by dcontador** [pysnippet/django-mermaid#17]
### Bug description

No explaining in the documentation, no indication of it being supported at all, how to deploy in a production environment without Internet connection.

### Reproduction steps

1. Install library and setup in Django project
2. Run any manager task
3. Manager fails in urllib because cannot connect to CDN, presumably

**Comment by ArtyomVancyan** [comment]
Hi @dcontador. I did not get it. You do not have an internet connection on your server?

CDN must be accessible to all, be it a server or an ordinary host. It installs the specified mermaid bundle once on the start and uses it without requiring an internet connection.

**Comment by ArtyomVancyan** [comment]
Also, note in README [Mermaid version](https://github.com/pysnippet/django-mermaid#mermaid-version) section:

> Make sure the version you specify is available on the [mermaid CDN](https://cdnjs.com/libraries/mermaid), and has the **mermaid.min.js** file.

So, if you see an error on installation that is not related to having an internet connection, then please check it.

Hope this information will be useful. Please reply with actual error messages or screenshots for fixing the issue more efficiently.

**Comment by ArtyomVancyan** [comment]
I am closing the issue. If you are still stuck on it, please reopen it, and do not forget to add the information mentioned above to fix it.
